### ISSUE TITLE
CentOS 7 runners created at each puppet run due to wrong config.toml location

### ISSUE THREAD

**Issue by gwarf** [frankiethekneeman/puppet-gitlab-ci-multi-runner#6]
Hi,
On `CentOS 7.1.1503` with `gitlab-ci-multi-runner-0.5.2-1.x86_64`, the runners are created at each pass as the location of the `config.toml` is `/home/gitlab_ci_multi_runner/.gitlab-runner/config.toml` not `/home/gitlab_ci_multi_runner/config.toml` as checked in the [only_if of the exec resource](https://github.com/frankiethekneeman/puppet-gitlab-ci-multi-runner/blob/1.7/manifests/runner.pp#L148).
I am only testing on CentOS 7 so I don't know how you would like to handle this issue. I can provide a PR based on you preference if you want.
 I am currently using a fork with just the path fixed in the only_if line, see gnubila-france/puppet-gitlab-ci-multi-runner@7d76a041d it would probably break with older runner versions.
Best,
Baptiste

**Comment by frankiethekneeman** [comment]
Is this just an RHEL 7+ thing?  Or is it a result of re-architecting under v0.5.2.1?  Unfortuntately, I really only have one image to test on myself, and it's CentOS 6.  Maybe @donoftime can weigh in on how this operates in a Ubuntu environment.  If it is truly a RHEL issue, probably the solution to this is similar to the `$serviceFile` solution under init.pp:

```
$tomlFile = $::osfamily ? {
    'redhat'   => $::operatingsystemrelease ? {
        /^[56].*/ => '/home/gitlab_ci_multi_runner/config.toml',
        default      => '/home/gitlab_ci_multi_runner/.gitlab-runner/config.toml',
    },
    default => '/home/gitlab_ci_multi_runner/config.toml',
}
```

Though, if it's a version issue, perhaps the best way would be to reference the installed version directly:

```
$tomlFile = $gitlab_ci_multi_runner::version ? {
    /^0\.[0-4]\..*/ => '/home/gitlab_ci_multi_runner/config.toml'
    default         => '/home/gitlab_ci_multi_runner/.gitlab-runner/config.toml'
}
```

**Comment by donoftime** [comment]
Here is the [commit from @ayufan](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/commit/fdeeef4be8f23b38e7696102a5f510acfca74a06) that introduced that change into the runner package. Looking at the branches that commit is on, it looks like it was only introduced in versions 5 and later.

![git branch --contains](https://cloud.githubusercontent.com/assets/5498070/9664992/44647d38-523b-11e5-9ce7-5015051818bf.png)

So we probably want to take @frankiethekneeman's second option and conditionally check based on the version of the runner package, rather than the OS family.

---

As for playing around with other distributions to see how they work, [vagrant](https://www.vagrantup.com/) is great for that. It can get you pretty much any distro you want in about 5 mins - assuming it hasn't downloaded the box already. I don't actually use Ubuntu for serious stuff, I just used vagrant to give it a whirl to make sure I wasn't breaking everyone :smile:

**Comment by gwarf** [comment]
Yes vagrant is very handy, but it still needs some time for testing :)
Being curious, what is your test workflow? Are you running a puppet master in a dedicated vagrant VM, in the test VM or in the host? Or are you using only puppet apply in the test VM?
I will craft a PR with the proposed solution.

**Comment by donoftime** [comment]
I was just mounting the directory with the puppet module from my laptop into the VM at `/etc/puppet/modules/gitlab-ci-multirunner`, and then doing a `puppet apply -e "class {'gitlab_ci_multi_runner': }"`.

**Comment by gwarf** [comment]
Nice, a quick and efficient for testing the main manifest :)
